default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

  # Performance optimizations
  checkout_timeout: 5
  reaping_frequency: 10

  # Connection pooling
  idle_timeout: 300

development:
  <<: *default
  database: agentic_rails_development
  username: agentic_rails
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

  # Enable query logging
  min_messages: log

test:
  <<: *default
  database: agentic_rails_test
  username: agentic_rails
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>

  # Read replica configuration
  replica:
    url: <%= ENV['DATABASE_REPLICA_URL'] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>

  # Performance tuning
  statement_timeout: 10000 # 10 seconds
  connect_timeout: 10

  # SSL configuration
  sslmode: require
  sslcert: <%= ENV['DATABASE_SSL_CERT'] %>
  sslkey: <%= ENV['DATABASE_SSL_KEY'] %>
  sslrootcert: <%= ENV['DATABASE_SSL_ROOT_CERT'] %>